# Site specific settings
title: "OggCamp 18"
name: "OggCamp 18 - A celebration of Free Culture, Free and Open Source Software, hardware hacking, digital rights, and all manner of collaborative activites."
keywords: "Free Culture, OggCamp, Open Source, Free Software, Creative Commons, Unconference, United Kingdom, UK, England, Great Britain"
baseurl: ""
url: "https://oggcamp.github.io"
description: "OggCamp 18"
cover: "/assets/img/cover.svg"
fanpage_id: ""

# Site general settings
lang: "en"
lang_alternate: ""
ssl: false # It will redirect to https

# Media
# Just the shortname:
# facebook: lampiaosec # Rigth
# facebook: facebook.com/lampiaosec # Wrong
twitter: oggcamp
facebook: oggcamp
github: oggcamp
google: 114120215314425775951
telegram: AAAAAAsF-xo4ol9jAjNW8A
joindin: oggcamp-18-2018

# Build settings
markdown: kramdown
permalink: /:categories/:title/
